CFG ?= Debug
PROJ ?= Block

build :
	@mkdir -p $(CFG)
	make -f makeprj.px2 CFG=$(CFG)
	
ifeq (ARM,$(findstring ARM,$(CFG)))
	@cp -fp ./$(CFG)/libARMBlock.so ../../../../Bin/Data/$(PROJ)/
else
	@cp -fp ./$(CFG)/libBlock.so ../../../../Bin/Data/$(PROJ)/
endif

clean :
	make clean -f makeprj.px2 CFG=$(CFG)
	@rm -rf $(CFG)
