# ServerLinuxRobot

CFG ?= Debug

build :
	make CFG=$(CFG) -f makeapp.px2 APP=ServerLinuxRobot
	
	@cp -fp ./ServerLinuxRobot.$(CFG) ../../../../Bin/
		
clean :
	clean CFG=$(CFG) -f makeapp.px2 APP=ServerLinuxRobot
